use madangdb;

-- 4-1 example
SELECT ABS(-78), ABS(+78);
SELECT ROUND(321.141592, 2);
SELECT ROUND(321.141592, -1);
SELECT ROUND(321.141592, 0);

-- 4-3 example
SELECT CUSTID, ROUND(AVG(SALEPRICE), -2) FROM ORDERS GROUP BY CUSTID;

-- 4-4 example
SELECT BOOKID, REPLACE(BOOKNAME, '야구', '농구') BOOKNAME, PUBLISHER, PRICE FROM BOOK;

-- 4-5 example
SELECT BOOKNAME '제목', CHAR_LENGTH(BOOKNAME) '문자수', LENGTH(BOOKNAME) '바이트수' FROM BOOK WHERE PUBLISHER = '굿스포츠'; 

-- 4-6 example
SELECT SUBSTR(NAME, 1, 1) '성', COUNT(*) '인원' FROM CUSTOMER GROUP BY SUBSTR(NAME, 1, 1);

-- 4-7 example
SELECT ORDERID '주문번호', ORDERDATE '주문일', ADDDATE(ORDERDATE, INTERVAL 10 DAY) '확정' FROM ORDERS;

-- 4-8 example
SELECT ORDERID '주문번호', DATE_FORMAT(ORDERDATE, '%Y-%m-%d') '주문일', custid '고객번호', bookid'도서번호'
FROM ORDERS WHERE ORDERDATE= STR_TO_DATE('20240707', '%Y%m%d');
